// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzX9StrXc_1R6VSB2jgYsX6Pd4j9ner54',
    appId: '1:774378873136:web:656d28dcb39ce12ee268f5',
    messagingSenderId: '774378873136',
    projectId: 'fundoo-notes-app-ecf23',
    authDomain: 'fundoo-notes-app-ecf23.firebaseapp.com',
    storageBucket: 'fundoo-notes-app-ecf23.appspot.com',
    measurementId: 'G-8739R1PFNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLxQnjQgTdhijIvWWfCoPMffyBddNADJ0',
    appId: '1:774378873136:android:c68aaaea6313169be268f5',
    messagingSenderId: '774378873136',
    projectId: 'fundoo-notes-app-ecf23',
    storageBucket: 'fundoo-notes-app-ecf23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4vNVQDdJQp6LiiQn1RV4jzsZwTTeL8rI',
    appId: '1:774378873136:ios:31ffc0a5151b1475e268f5',
    messagingSenderId: '774378873136',
    projectId: 'fundoo-notes-app-ecf23',
    storageBucket: 'fundoo-notes-app-ecf23.appspot.com',
    iosClientId: '774378873136-r8egm8f0mabao9euio0f99s9aj1t55lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fundooNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4vNVQDdJQp6LiiQn1RV4jzsZwTTeL8rI',
    appId: '1:774378873136:ios:14b3568717f93528e268f5',
    messagingSenderId: '774378873136',
    projectId: 'fundoo-notes-app-ecf23',
    storageBucket: 'fundoo-notes-app-ecf23.appspot.com',
    iosClientId: '774378873136-n36fjhatvge357k47oq76t63el1sqgrm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fundooNotes.RunnerTests',
  );
}
